name: Build Keycloak
description: Builds Keycloak providing Maven repository with all artifacts

runs:
  using: composite
  steps:
    - id: setup-java
      name: Setup Java
      uses: ./.github/actions/java-setup

    - id: maven-cache
      name: Maven cache
      uses: ./.github/actions/maven-cache
      with:
        create-cache-if-it-doesnt-exist: true

    - id: phantomjs-cache
      name: PhantomJS cache
      uses: ./.github/actions/phantomjs-cache

    - id: frontend-plugin-cache
      name: Frontend Plugin Cache
      uses: ./.github/actions/frontend-plugin-cache

    - id: build-keycloak
      name: Build Keycloak
      shell: bash
      # By using "dependency:resolve", it will download all dependencies used in later stages for running the tests
      run: |
        ./mvnw install dependency:resolve -V -e -DskipTests -DskipExamples ${{ env.MVN_PROFILES}}
