name: Build Keycloak, Create Release and Publish Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Set version
        run: ./set-version.sh ${{ steps.tag.outputs.new_tag }}

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak
        with:
          upload-m2-repo: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: quarkus/dist/target/keycloak-*.tar.gz
          tag_name: ${{ steps.tag.outputs.new_tag }}
