name: Create Release

on:
  workflow_run:
    workflows: [Bump version]
    types:
      - completed

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch_depth: 0

      - name: Get Latest Tag
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Set Version
        run: ./set-version.sh ${{ steps.latest-tag.outputs.tag }}

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: quarkus/dist/target/keycloak-*.tar.gz
          tag_name: ${{ steps.latest-tag.outputs.tag }}
