name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Version
        run: ./set-version.sh ${{ github.ref_name }}

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: quarkus/dist/target/keycloak-*.tar.gz
          tag_name: ${{ steps.tag.outputs.new_tag }}
